apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-pull-secret
  namespace: kantraformation  # Facultatif, sinon ce sera le namespace par défaut
data:
  .dockerconfigjson: cmFraXpvdWFyaTpkY2tyX3BhdF9ERGxsS0I0aGNZV3ctMTlPRC1NdmpWWnpaQU0=
type: kubernetes.io/dockerconfigjson
