apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  namespace: kantraformation  # Facultatif si vous voulez le mettre dans un namespace spécifique
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJhdXRoIjogImNtRnJhWHB2ZFdGeWFUcGtZMnR5WDNCaGRGOTRZWE5UVkVWbmVIQTNPV2w2VjBkWFZ6WXpXbXBDUkVWb2VVaz0iCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
