apiVersion: v1
kind: Service
metadata:
  name: kantraformation-back
  namespace: default
spec:
  externalIPs:
    - 10.0.0.5
  selector:
    app: kantraformation-back
  ports:
    - nodePort: 30001
      protocol: TCP
      port: 8094
      targetPort: 8094
  type: LoadBalancer
