apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kantraformation
  namespace: argocd
spec:
  destination:
    namespace: kantraformation
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: argocd-apps/kantraformation
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
