apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    root-password: AgBIp//tlE7/jVCVKwxl/IxkCsb1SlqQ+iKNHjHO7M7mMaCI4dNjxvomoJ3HwbCvZrDEeXB2zhnZWz7IUkxNJ/D0uZuCu88nJq/xgYhASGtHuNzjrSQfvmY3WBfbBb34zRxuFlAFecgrOwYIZZK5+/X2J86XlFf74VypFsJ4M7fNRL8nw2tBcGdOqgGli8b7U0l/R1T32XDTQX9KKLzpXrWJ8NxhDPRQemTuBbRNzlg0CF9Wdq36jB8KTf3Xr1Ltwe6jGw8HSsRDsjeoKsYMUEFpt89AG689RhOuMExqy7g5oc2QnS+0TG36dgzU6mE7QUB6xHPBpQuSjxGl8R3/LCTi1ys/EWQx+jf3SVrTChNGfGob4uTg87XhnFRPIECU9L/1tMIRPMHMKwrc2875yV/QqL6/Yxg3UWzsifZPnLnhTsIckq+GLGLJ2G4rAGZJifrqHHdLk9LaGTNTUN50cbIqbAXH6MifIYdljwe0Bs3LO4f1WKIqCAPvcYw/cMa84++1EAOK3uTlo0v9BYvhpDZR5i1sfTNbvZrfxHS9KeI0T7S0fm8m48ZfB8ZhZv4uvlCJ6yo6kDoshM+CBlro6dsFLsGcU+1BNenuMsv0fCBmqVDqlkj0LctEDOk4vvmWleW/Akr6E57OxnRSP4Y3mTYLacK8X08rSeCoilRTeM4lwoXmxIckuJrIhhwojEUCTmBAvrLhavtTcNTZW1nh
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mysql-secret
      namespace: default
    type: Opaque
