apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kantraformation-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
