apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kantraformation-db-pvc
  namespace: kantraformation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: kantraformation-db-pv
