apiVersion: apps/v1
kind: Deployment
metadata:
  name: kantraformation
  labels:
    app: kantraformation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kantraformation
  template:
    metadata:
      labels:
        app: kantraformation
    spec:
      containers:
        - name: kantraformation
          image: rakizouari/kantrafront:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: httpport
          env:
            - name: BACKEND_URL
              value: "http://kantraformation-back:8094" 
          resources:
            limits:
              cpu: 100m
              memory: 700Mi
            requests:
              cpu: 50m
              memory: 700Mi
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/share/nginx/html/assets/
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: github-packages-pull-secret
      restartPolicy: Always
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: kantraformation-uploadedfiles-pvc
