apiVersion: v1
kind: Service
metadata:
  name: kantraformation-front
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: kantraformation-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 10.0.0.4
