apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kantraformation-uploadedfiles-pvc
  namespace: kantraformation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  hostPath:
    path: "/mnt/data"

