apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kantraformation-uploadedfiles-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path  # Doit correspondre au PVC s'il utilise la même classe
  hostPath:
    path: /mnt/data/kantraformation-uploadedfiles
