apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kantraformation-uploadedfiles-pvc
  namespace: kantraformation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
