apiVersion: v1
kind: PersistentVolume
metadata:
  name: kantraformation-uploadedfiles-pv
  namespace: kantraformation
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/kantraformation-uploadedfiles"
